name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - macOS
    name: env
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          action: build
          code-coverage: true
          warnings-as-errors: true
          configuration: debug
