name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: env
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: ZjoocHelper.xcodeproj
          scheme: ZjoocHelper
          destination: platform=macOS
          action: build
